# Generated by Django 4.0.5 on 2022-06-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musinsa_model',
            fields=[
                ('musinsa_key', models.IntegerField(primary_key=True, serialize=False)),
                ('musinsa_image', models.TextField()),
                ('musinsa_link', models.TextField()),
            ],
            options={
                'db_table': 'musinsa',
            },
        ),
    ]
