# Generated by Django 4.0.5 on 2022-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0002_mixxo_model_spao_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='mixxo_rank',
            fields=[
                ('mixxo_key', models.IntegerField(primary_key=True, serialize=False)),
                ('mixxo_rank_name', models.CharField(max_length=100)),
                ('mixxo_rank_link', models.TextField()),
            ],
            options={
                'db_table': 'mixxo_rank',
            },
        ),
        migrations.CreateModel(
            name='musinsa_rank',
            fields=[
                ('musinsa_rank_key', models.IntegerField(primary_key=True, serialize=False)),
                ('musinsa_rank_name', models.CharField(max_length=100)),
                ('musinsa_rank_link', models.TextField()),
            ],
            options={
                'db_table': 'musinsa_rank',
            },
        ),
        migrations.CreateModel(
            name='spao_rank',
            fields=[
                ('spao_key', models.IntegerField(primary_key=True, serialize=False)),
                ('spao_rank_name', models.CharField(max_length=100)),
                ('spao_rank_link', models.TextField()),
            ],
            options={
                'db_table': 'spao_rank',
            },
        ),
    ]
