# Generated by Django 4.0.5 on 2022-06-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0003_mixxo_rank_musinsa_rank_spao_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixxo_rank',
            old_name='mixxo_key',
            new_name='mixxo_rank_key',
        ),
        migrations.RenameField(
            model_name='spao_rank',
            old_name='spao_key',
            new_name='spao_rank_key',
        ),
    ]
